<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>astar.ico</ApplicationIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>AStar Development, Jason Barden</Authors>
        <Copyright>AStar Development, 2025</Copyright>
        <PackageProjectUrl>https://github.com/astar-development/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/astar-development/</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <DocumentationFile>$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AStar.Dev.Technical.Debt.Reporting" Version="0.2.1" />
        <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.1.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AStar.Dev.Utilities\AStar.Dev.Utilities.csproj" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <NoWarn>1701;1702;</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <NoWarn>1701;1702;</NoWarn>
    </PropertyGroup>

</Project>
