<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>astar.ico</ApplicationIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>AStar Development, Jason Barden</Authors>
        <Copyright>AStar Development, 2025</Copyright>
        <PackageProjectUrl>https://github.com/astar-development/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/astar-development/</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <DocumentationFile>$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>
  
  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2m69-gcr7-jv3q" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AStar.Dev.Technical.Debt.Reporting" Version="0.2.1" />
        <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.1.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AStar.Dev.Utilities\AStar.Dev.Utilities.csproj" />
        <ProjectReference Include="../AStar.Dev.FunctionalParadigm/AStar.Dev.FunctionalParadigm.csproj" />
    </ItemGroup>

  <ItemGroup>
      <None Update="Mappings.csv">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
  </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <NoWarn>1701;1702;</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <NoWarn>1701;1702;</NoWarn>
    </PropertyGroup>

</Project>
