// <auto-generated />
using System;
using System.Collections.Generic;
using AStar.Dev.Infrastructure.FilesDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.Infrastructure.FilesDb.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20260623223228_AddSearchCategoryIncludeInSearch")]
    partial class AddSearchCategoryIncludeInSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ConnectionStrings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScrapeConfigurationEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sqlite")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("ConnectionStrings", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.DeletionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("HardDeletePending")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("HardDeletePending");

                    b.Property<DateTimeOffset?>("SoftDeletePending")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SoftDeletePending");

                    b.Property<DateTimeOffset?>("SoftDeleted")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SoftDeleted");

                    b.HasKey("Id");

                    b.ToTable("DeletionStatus", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.DuplicatesDetails", b =>
                {
                    b.Property<DateTime>("DetailsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileAccessDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHandle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HardDeletePending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Instances")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MoveRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeletePending")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("vw_DuplicatesDetails", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EventOccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FileCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FileLastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Type", "AStar.Dev.Infrastructure.FilesDb.Models.Event.Type#EventType", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EventName");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EventType");
                        });

                    b.HasKey("Id");

                    b.ToTable("Event", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileAccessDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetailsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MoveRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileAccessDetail", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Celebrity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileClassification", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeletionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileAccessDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImageDetailId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DirectoryName", "AStar.Dev.Infrastructure.FilesDb.Models.FileDetail.DirectoryName#DirectoryName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("DirectoryName");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FileName", "AStar.Dev.Infrastructure.FilesDb.Models.FileDetail.FileName#FileName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("FileName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeletionStatusId");

                    b.HasIndex("FileAccessDetailId");

                    b.HasIndex("FileHandle")
                        .IsUnique();

                    b.HasIndex("FileSize");

                    b.HasIndex("ImageDetailId");

                    b.HasIndex("IsImage", "FileSize")
                        .HasDatabaseName("IX_FileDetail_DuplicateImages");

                    b.ToTable("FileDetail", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileNamePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileClassificationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileClassificationId");

                    b.ToTable("FileNamePart", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ImageDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ImageHeight");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ImageWidth");

                    b.HasKey("Id");

                    b.ToTable("ImageDetail", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ModelToIgnore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelToIgnore", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScrapeConfiguration", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeDirectories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BaseDirectoryFamous")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BaseSaveDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ScrapeConfigurationEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubDirectoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("ScrapeDirectories", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ScrapedTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("ScrapedTag", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.SearchCategories", b =>
                {
                    b.Property<int>("SearchConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastKnownImageCount")
                        .HasColumnType("int");

                    b.Property<int>("LastPageVisited")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("SearchConfigurationId", "Id");

                    b.ToTable("SearchCategories", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.SearchConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ImagePauseInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ScrapeConfigurationEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SearchStringPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SearchStringSuffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<float?>("SlowMotionDelay")
                        .HasColumnType("real");

                    b.Property<int>("StartingPageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Subscriptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SubscriptionsStartingPageNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionsTotalPages")
                        .HasColumnType("int");

                    b.Property<string>("TopWallpapers")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TopWallpapersStartingPageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TopWallpapersTotalPages")
                        .HasColumnType("int");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.Property<bool>("UseHeadless")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("SearchConfiguration", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.TagToIgnore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreImage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TagToIgnore", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.UserConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ScrapeConfigurationEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionCookie")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("UserConfiguration", "files");
                });

            modelBuilder.Entity("FileClassificationFileDetail", b =>
                {
                    b.Property<int>("FileClassificationsId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FileDetailsId")
                        .HasColumnType("TEXT");

                    b.HasKey("FileClassificationsId", "FileDetailsId");

                    b.HasIndex("FileDetailsId");

                    b.ToTable("FileClassificationFileDetail", "files");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ConnectionStrings", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeConfigurationEntity", "ScrapeConfigurationEntity")
                        .WithOne("ConnectionStrings")
                        .HasForeignKey("AStar.Dev.Infrastructure.FilesDb.Models.ConnectionStrings", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeConfigurationEntity");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileDetail", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.DeletionStatus", "DeletionStatus")
                        .WithMany()
                        .HasForeignKey("DeletionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.FileAccessDetail", "FileAccessDetail")
                        .WithMany()
                        .HasForeignKey("FileAccessDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.ImageDetail", "ImageDetail")
                        .WithMany()
                        .HasForeignKey("ImageDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeletionStatus");

                    b.Navigation("FileAccessDetail");

                    b.Navigation("ImageDetail");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileNamePart", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.FileClassification", null)
                        .WithMany("FileNameParts")
                        .HasForeignKey("FileClassificationId");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeDirectories", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeConfigurationEntity", "ScrapeConfigurationEntity")
                        .WithOne("ScrapeDirectories")
                        .HasForeignKey("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeDirectories", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeConfigurationEntity");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.SearchCategories", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.SearchConfiguration", "SearchConfiguration")
                        .WithMany("SearchCategories")
                        .HasForeignKey("SearchConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchConfiguration");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.SearchConfiguration", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeConfigurationEntity", "ScrapeConfigurationEntity")
                        .WithOne("SearchConfiguration")
                        .HasForeignKey("AStar.Dev.Infrastructure.FilesDb.Models.SearchConfiguration", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeConfigurationEntity");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.UserConfiguration", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeConfigurationEntity", "ScrapeConfigurationEntity")
                        .WithOne("UserConfiguration")
                        .HasForeignKey("AStar.Dev.Infrastructure.FilesDb.Models.UserConfiguration", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeConfigurationEntity");
                });

            modelBuilder.Entity("FileClassificationFileDetail", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.FileClassification", null)
                        .WithMany()
                        .HasForeignKey("FileClassificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.FilesDb.Models.FileDetail", null)
                        .WithMany()
                        .HasForeignKey("FileDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.FileClassification", b =>
                {
                    b.Navigation("FileNameParts");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.ScrapeConfigurationEntity", b =>
                {
                    b.Navigation("ConnectionStrings")
                        .IsRequired();

                    b.Navigation("ScrapeDirectories")
                        .IsRequired();

                    b.Navigation("SearchConfiguration")
                        .IsRequired();

                    b.Navigation("UserConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.FilesDb.Models.SearchConfiguration", b =>
                {
                    b.Navigation("SearchCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
