//HintName: OrderId.StrongId.g.cs
// <auto-generated/>
#nullable enable
namespace AStar.Dev.Source.Generators.Tests.Unit.StrongIdCodeGeneration;

public readonly partial struct OrderId(Guid value) : IEquatable<OrderId>
{
    private readonly Guid _value = value;

    public static implicit operator Guid(OrderId id) => id._value;
    public static explicit operator OrderId(Guid value) => new(value);

    public bool Equals(OrderId other) => EqualityComparer<Guid>.Default.Equals(_value, other._value);
    public override bool Equals(object? obj) => obj is OrderId other && Equals(other);
    public override int GetHashCode() => EqualityComparer<Guid>.Default.GetHashCode(_value);
    public override string ToString() => _value.ToString();

    public static OrderId New() => new(Guid.NewGuid());

    public static bool TryParse(string? s, out OrderId value)
    {
        bool ok = Guid.TryParse(s, out var g);
        value = ok ? new(g) : default;
        return ok;
    }
}
